---
title: Introduction to Recommendation System
author: Avishek Saha
date: '2023-12-25'
slug: []
categories:
  - Recommender system
tags:
  - Recommender system
subtitle: ''
lastmod: '2023-12-25T21:08:27-08:00'
authorLink: ''
description: ''
license: ''
images: []
featuredImage: ''
featuredImagePreview: ''
hiddenFromHomePage: no
hiddenFromSearch: no
twemoji: no
lightgallery: yes
ruby: yes
fraction: yes
fontawesome: yes
linkToMarkdown: yes
rssFullText: no
toc:
  enable: yes
  auto: yes
code:
  copy: yes
  maxShownLines: 50
math:
  enable: no
mapbox: ~
share:
  enable: yes
comment:
  enable: yes
library:
  css: ~
  js: ~
seo:
  images: []
---

A recommendation system, also known as a recommender system, is a specialized type of information filtering system rooted in artificial intelligence and machine learning. Leveraging Big Data, these systems analyze diverse criteria such as past purchases, search history, demographic information, and other relevant factors to suggest or recommend additional products or items to consumers. By tailoring suggestions to individual users, recommendation systems play a crucial role in helping users explore and discover products and services they might not have encountered independently.

# Key Components of a Recommendation System
Recommendation systems build on three core components.

## Collector
The collector’s role is to know what is in the collection of things that may be rec‐
ommended, and the necessary features or attributes of those things. Note that this
collection is often a subset based on context or state.

## Ranker
The ranker’s role is to take the collection provided by the collector and order some or
all of its elements, according to a model for the context and user.

## Server
The server’s role is to take the ordered subset provided by the ranker, ensure that the
necessary data schema is satisfied—including essential business logic—and return the
requested number of recommendations.

# Types of Recommendation System:
1. Popularity based recommender system
2. Classification
3. Content based recommender systems
4. Collaborative filtering
5. Hybrid approaches

## Popularity based recommender system
Can be seen platforms like Netflix, Newspapers site, amazon, spotify. So, it basically suggests you the products or things that are currently popular in that region or popular among the users like you.